import{a as S,S as w,i as c}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const i={form:document.querySelector(".form"),input:document.querySelector("#user-input"),button:document.querySelector(".search-button"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMore:document.querySelector(".load-button")},v="42305784-5d55228baaa9a6392a5b2668b",M="https://pixabay.com/api/",A=15;async function m(a,r=1){const o={key:v,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:A};try{return(await S.get(M,{params:o})).data}catch(s){throw console.error("Error fetching images from Pixabay API:",s),s}}let d;function g(a){const r=a.map(({webformatURL:o,largeImageURL:s,tags:e,likes:t,views:l,comments:P,downloads:E})=>`<li class="gallery-item">
        <a href="${s}">
          <img src="${o}" alt="${e}" title="${e}"/>
          <div class="info">
            <h3>Likes</h3>
            <p>${t}</p>
            <h3>Views</h3>
            <p>${l}</p>
            <h3>Comments</h3>
            <p>${P}</p>
            <h3>Downloads</h3>
            <p>${E}</p>
          </div>
        </a>
      </li>`).join("");i.gallery.insertAdjacentHTML("beforeend",r),d?d.refresh():d=new w(".gallery a",{captionsData:"alt",captionDelay:250})}function q(){i.gallery.innerHTML=""}function p(){i.loader.classList.remove("is-hidden")}function y(){i.loader.classList.add("is-hidden")}function L(){i.loadMore.classList.remove("is-hidden")}function u(){i.loadMore.classList.add("is-hidden")}function b(){c.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"})}let n=1,h="",f=0;const I=15;async function R(a){a.preventDefault();const r=i.input.value.trim();if(r===""){c.error({message:"Please enter something to search for images!",position:"topRight"});return}h=r,n=1,q(),u(),p();try{const o=await m(h,n);if(o.hits.length===0){c.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}f=Math.ceil(o.totalHits/I),g(o.hits),n<f?L():b()}catch(o){console.error("Error during image search:",o),c.error({message:"Unfortunately, there was an error loading images. Please try again later!",position:"topRight"})}finally{y()}}i.loadMore.addEventListener("click",async()=>{n+=1,u(),p();try{const a=await m(h,n);g(a.hits);const r=i.gallery.firstElementChild.getBoundingClientRect().height;window.scrollBy({behavior:"smooth",top:r*2}),n===f?(b(),u()):L()}catch(a){console.error("Error loading additional images:",a),c.error({message:"Sorry, there was an error loading more images. Please try again later.",position:"topRight"}),u()}finally{y()}});i.form.addEventListener("submit",R);
//# sourceMappingURL=index.js.map
