import{a as P,S as v,i as c}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const i={form:document.querySelector(".form"),input:document.querySelector("#user-input"),button:document.querySelector(".search-button"),gallery:document.querySelector(".gallery"),loadMore:document.querySelector(".load-button"),loader:document.querySelector("#loader")},E="42305784-5d55228baaa9a6392a5b2668b",M="https://pixabay.com/api/";async function m(a,r=1){const o={key:E,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};try{return(await P.get(M,{params:o})).data}catch(s){throw console.error("Sorry, there is some problem. Please try again later.",s),s}}let u;function g(a){const r=a.map(({webformatURL:o,largeImageURL:s,tags:e,likes:t,views:l,comments:S,downloads:w})=>`<li class="gallery-item">
          <a href="${s}">
            <img src="${o}" alt="${e}" title="${e}"/>
            <div class="info">
              <h3>Likes</h3>
              <p>${t}</p>
              <h3>Views</h3>
              <p>${l}</p>
              <h3>Comments</h3>
              <p>${S}</p>
              <h3>Downloads</h3>
              <p>${w}</p>
            </div>
          </a>
        </li>`).join("");i.gallery.insertAdjacentHTML("beforeend",r),u?u.refresh():u=new v(".gallery a",{captionsData:"alt",captionDelay:250})}function q(){i.gallery.innerHTML=""}function p(){i.loader.classList.remove("is-hidden")}function y(){i.loader.classList.add("is-hidden")}function L(){i.loadMore.classList.remove("is-hidden")}function d(){i.loadMore.classList.add("is-hidden")}function b(){c.info({message:"Sorry, you have reached the end of the search results.",position:"topRight"})}let n=1,h="",f=0;const R=15;i.loadMore.addEventListener("click",async()=>{n+=1,d(),p();try{const a=await m(h,n);g(a.hits);const r=i.gallery.firstElementChild.getBoundingClientRect().height;window.scrollBy({behavior:"smooth",top:r*2}),n===f?(b(),d()):L()}catch(a){console.error("Error loading additional images:",a),c.error({message:"Sorry, there was an error loading more images. Please try again later.",position:"topRight"}),d()}finally{y()}});async function $(a){a.preventDefault();const r=i.input.value.trim();if(r===""){c.error({message:"Please enter something to search for images!",position:"topRight"});return}h=r,n=1,q(),d(),p();try{const o=await m(h,n);if(o.hits.length===0){c.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}f=Math.ceil(o.totalHits/R),g(o.hits),n<f?L():b()}catch(o){console.error("Error during image search:",o),c.error({message:"Unfortunately, there was an error loading images. Please try again later!",position:"topRight"})}finally{y()}}i.form.addEventListener("submit",$);
//# sourceMappingURL=index.js.map
